// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaKIssfZidqmYRXPkJJXPzFomge_z2WeI',
    appId: '1:221631606516:web:fa82fda60ccca5d594b8a1',
    messagingSenderId: '221631606516',
    projectId: 'ncba-clone',
    authDomain: 'ncba-clone.firebaseapp.com',
    storageBucket: 'ncba-clone.appspot.com',
    measurementId: 'G-NB04W21L4P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5bqoJuTdESj0pqBRPq2LXt-m21UeNF2U',
    appId: '1:221631606516:android:585e98543db916eb94b8a1',
    messagingSenderId: '221631606516',
    projectId: 'ncba-clone',
    storageBucket: 'ncba-clone.appspot.com',
  );
}
